FROM elixir:1.7.3

ENV HOME /home/shared
WORKDIR /app

# Install hex (Elixir package manager)
RUN mix local.hex --force

# Install rebar (Erlang build tool)
RUN mix local.rebar --force

RUN mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez

RUN apt-get update && apt-get install -y inotify-tools
